import { REDUCERS } from './reducers';

export enum GAME_ACTIONS {
  NEW = 'NEW',

  SELECT_CELL = 'SELECT_CELL',
  PLACE_IM_VAL = 'PLACE_IM_VAL',
  ADD_ERROR = 'ADD_ERROR',
  SUB_ERROR = 'SUB_ERROR',

  // TIMER
  TIMER_START = 'TIMER_START',
  TIMER_STOP = 'TIMER_STOP',
  TIMER_RESET = 'TIMER_RESET',
  TIMER_GET_MSECS = 'TIMER_GET_MSECS',
}

export enum SETTINGS_ACTIONS {
  SET_DIFFICULTY = 'SET_DIFFICULTY',
  SET_NAME = 'SET_NAME',
  CLEAR_NAME = 'CLEAR_NAME',
}

export const ACTIONS = {
  [REDUCERS.GAME]: GAME_ACTIONS,
  [REDUCERS.SETTINGS]: SETTINGS_ACTIONS,
};
