export enum GAME_ACTIONS {
  INIT = 'INIT',
  SELECT_CELL = 'SELECT_CELL',
  UPDATE_BOARD = 'UPDATE_BOARD',
  PLACE_IM_VAL = 'PLACE_IM_VAL',

  // TIMER
  TIMER_START = 'TIMER_START',
  TIMER_STOP = 'TIMER_STOP',
  TIMER_RESET = 'TIMER_RESET',
}

export const ACTIONS = {
  GAME: GAME_ACTIONS,
};
